main:
- name: "Home"
  pageRef: /
  weight: 1
- name: "Posts"
  pageRef: /posts
  weight: 5
- name: "GameDev"
  url: "https://gamedev.shaneyao.com"
  weight: 20
- name: "Notes"
  url: "https://notes.shaneyao.com"
  weight: 20
