main:
- name: "主页"
  pageRef: /
  weight: 1
- name: "博客"
  pageRef: /posts
  weight: 5
- name: "游戏开发"
  url: "https://gamedev.shaneyao.com"
  weight: 20
  
- name: "笔记"
  url: "https://notes.shaneyao.com"
  weight: 20

footer:
- name: "关于本站"
  pageRef: "/about/"